algorithms:
  title: Algorithms
  definition: algorithms are this
big data:
  title: Big data
  definition: blah
entropy:
  title: Entropy
  definition: Blfdskfdsl
complexity:
  title: Complexity
  definition: kfjldsajfd
